### ISSUE TITLE
Chat: Remove top left icon

### ISSUE THREAD

**Issue by ngoiyaeric** [QueueLab/MapGPT#16]
There is a favicon on the top left of the chat. This should be removed.

**Comment by rosaleeen** [comment]
i can work on this issue!!

**Comment by ngoiyaeric** [comment]
You've been assigned this issue.

**Comment by ngoiyaeric** [comment]
hi @rosaleeen https://github.com/ngoiyaeric/labs look through this codebase to look for clues for how to complete this assigned issue. Would be nice to have it done by end of day.
