### ISSUE TITLE
Chat: Earth theme Links turn Green

### ISSUE THREAD

**Issue by ngoiyaeric** [QueueLab/MapGPT#26]
**Is your feature request related to a problem? Please describe.**
Change colour of generated links to from grey to green. 

**Describe the solution you'd like**
All links including question suggestions. 

**Describe alternatives you've considered**
Grass Green Colour
<img width="762" alt="Screen Shot 2024-05-31 at 9 49 57 AM" src="https://github.com/QueueLab/MapGPT/assets/115367894/dfba23e9-226b-404a-8d36-20a6022c17c9">

**Additional context**
You're welcome to propose a shade of green you like.

**Comment by rosaleensiroosi** [comment]
hi, i can do this issue! just for clarification, this issue entails changing both the colour of the suggested questions on the first page and within the related portion upon asking a question? i have included screenshots of the latter case. thanks! :)
<img width="1362" alt="image" src="https://github.com/QueueLab/MapGPT/assets/171291607/289d508e-dc7e-4239-88d8-414f63cc67fe">

**Comment by ngoiyaeric** [comment]
Yes

**Comment by rosaleensiroosi** [comment]
i have changed the colour of the links and have included screenshots of the new view in this comment -- it isn't the grass green colour (i found it was a little harsh with the beige colour) though, is it still all right for you? if so, i can create a pull request with this update! :)
<img width="844" alt="Screenshot 2024-06-04 at 11 14 34 PM" src="https://github.com/QueueLab/MapGPT/assets/171291607/2e8a5ec6-e5b4-48dc-b3d8-9aa983531f70">
<img width="861" alt="Screenshot 2024-06-04 at 11 14 45 PM" src="https://github.com/QueueLab/MapGPT/assets/171291607/f3de86dc-55a1-4208-83ff-29f9272f1acb">

**Comment by ngoiyaeric** [comment]
Hi Rosaleen I like the shade of green you picked, everything looks good however I had updated these two issues you're working on. Could you toggle these theme changes for the system theme and rename it to Earth. As for the light and dark themes leave them as they were.
