### ISSUE TITLE
(Map/Chat): Earth theme background light beige

### ISSUE THREAD

**Issue by ngoiyaeric** [QueueLab/MapGPT#27]
**Is your feature request related to a problem? Please describe.**
Change light mode to have a paper like light beige colour. 

**Describe the solution you'd like**
Light mode should default to this colour, system and dark mode should stay the same.

**Comment by rosaleensiroosi** [comment]
i can do this! :)

**Comment by ngoiyaeric** [comment]
Can you experiment with these two issues, turning the system theme to earth theme when toggled for these colour changes.
