### ISSUE TITLE
Unhandled runtime error: request for mapbox api key

### ISSUE THREAD

**Issue by rosaleensiroosi** [QueueLab/MapGPT#29]
**Describe the bug**
Unhandled runtime error when visiting 'http://localhost:3000' after running bun dev. Is it necessary to create a MapBox account? If so, is there a business account we should use (since a personal account requires credit card information to be entered)?

**To Reproduce**
Steps to reproduce the behaviour:
1. complete all instructions in the README.md.
2. visit 'http://localhost:3000'.

**Expected behavior**
To see the program run locally.

**Screenshots**
<img width="978" alt="image" src="https://github.com/QueueLab/MapGPT/assets/171291607/9f574081-6dfe-4e8a-a9fb-96cf53db5ba6">

**Comment by ngoiyaeric** [comment]
Mapbox has a default access token after signing up for a free account. 
https://docs.mapbox.com/accounts/guides/tokens/#default-public-access-token
